name: Shell script for Ascii 

on:
    push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v7

        - name: List Repo Files
          run: ls -ltra

        - name: Execute Shell script
          run: |
             chmod +x ascii-script.sh
             ./ascii-script.sh